# Generated by Django 5.1.2 on 2024-10-28 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('order', '0002_alter_cartitem_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.shopprofile'),
        ),
    ]
